#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"

# Install config files (if they don't already exist)
mkdir -p $HOME/.config/leanhrpt/
if [ ! -e "$HOME/.config/leanhrpt/presets.ini" ]; then
    cp "${HERE}/presets.ini" "$HOME/.config/leanhrpt/presets.ini"
fi
if [ ! -e "$HOME/.config/leanhrpt/calibration.ini" ]; then
    cp "${HERE}/calibration.ini" "$HOME/.config/leanhrpt/calibration.ini"
fi

export PATH="${HERE}/usr/bin/:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/"

EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | cut -d "=" -f 2)
exec "${EXEC}" "$@"
