#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"

export PATH="${HERE}/usr/bin/:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/"

EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | cut -d "=" -f 2)
exec "${EXEC}" "$@"
